apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: vpromc
  name: vprocache01
spec:
  ports:
  - port: 11211
    protocol: TCP
    targetPort: vpromc-port
  selector:
    app: vpromc
status:
  loadBalancer: {}
